version: 0.2
env:
    variables:
      SONAR_HOST_URL: http://23.23.18.123:9000
      SONAR_TOKEN: d87c1e1a56438dc1b3db6d5219c31119550ca058
phases:
  install:
    runtime-versions:
      java: latest
  build:
    commands:
      - mvn verify sonar:sonar -Dsonar.projectKey=Javaproject-0 -Dsonar.host.url=$SONAR_HOST_URL -Dsonar.login=$SONAR_TOKEN
      - sleep 5
      - |- 
        quality_status=$(curl -s -u $SONAR_TOKEN: $SONAR_HOST_URL/api/qualitygates/project_status?projectKey=Javaproject-0 | jq -r '.projectStatus.status')
        echo "Sonar analysistatus is $quality_status"; 
        if [ "$quality_status" = "ERROR" ] ; then exit 1;fi
