version: 0.2
env:
    secrets-manager:
      SONAR_TOKEN: "dev/sonarqube/token:SONAR_TOKEN"
phases:
  install:
    runtime-versions:
      java: corretto17 # Pin to a specific Java version for reproducible builds
  build:
    commands:
      - mvn verify sonar:sonar -Dsonar.projectKey=Javaproject-0 -Dsonar.host.url=$SONAR_HOST_URL -Dsonar.login=$SONAR_TOKEN
      - sleep 5
      - |- 
        quality_status=$(curl -s -u $SONAR_TOKEN: $SONAR_HOST_URL/api/qualitygates/project_status?projectKey=Javaproject-0 | jq -r '.projectStatus.status')
        echo "Sonar analysistatus is $quality_status"; 
        if [ "$quality_status" = "ERROR" ] ; then exit 1;fi