version: 0.2
phases:
  install:
    runtime-versions:
      java: latest
  build:
    commands:
      - mvn verify sonar:sonar -Dsonar.projectKey=Javaproject-0 -Dsonar.organization=Javaproject-0 -Dsonar.host.url=https://sonarcloud.io -Dsonar.token=94f46db1a07b0621629e47bfe54e57df445e6c59

